const DesaWisata = [
  {
    id_desa: "DESA-0501",
    provinsi: "Jawa Barat",
    kabupaten: "Bandung",
    nama_desa: "Desa Cimahi",
    nama_popular: "Lembang Indah",
    alamat: "Jl. Lembang No. 123",
    jenis_wisata: "Wisata Alam",
    pengelola: "Pak Joko",
    nomor_telepon: "081234567890",
    email: "defa12@wisata.com",
    kategori_desa: "Maju",
    jenis_wisata: ["wisata alam", "wisata budaya"],
    status: "aktif",
    keterangan: "Desa Wisata Desa Cimahi telah diverifikasi oleh admin",
    partisipasi_masyarakat: 95,
    keragaman_paket_wisata: 88,
    akses_tempat_wisata: 90,
    keramahan_difabel: 80,
    fasilitas_tempat_wisata: 95,
    produk_tempat_wisata: 85,
    rata_rata_nilai: 88,
    penjelasan_umum: "Deskripsi umum tentang desa wisata ini",
    fasilitas: ["parkir", "toilet", "tempat ibadah", "tempat bermain anak", "tempat penginapan", "tempat makan", "tempat souvenir", "tempat wisata edukasi", "tempat wisata alam", "tempat wisata budaya", "spot foto"],
    cover_desa: "https://example.com/cover.jpg",
    galeri_desa: ["https://www.youtube.com/watch?v=tsuO ", "https://www.youtube.com/watch?v=tsuO "],
    url_video: ["https://www.youtube.com/watch?v=tsuO ", "https://www.youtube.com/watch?v=tsuO "],
    atraksi: [
      { id: 1, nama: "Atraksi 1", jenis_atraksi: "wisata alam", gambar: "https://example.com/image1.jpg ", likes: 100 },
      { id: 2, nama: "Atraksi 2", jenis_atraksi: "wisata budaya", gambar: "https://example.com/image1.jpg ", likes: 34 },
    ],
    penginapan: [
      { nama: "Penginapan 1", harga: 200000, gambar: "https://example.com/inn1.jpg " },
      { nama: "Penginapan 2", harga: 300000, gambar: "https://example.com/inn2.jpg " },
    ],
    paket_wisata: [
      { nama: "Paket 1", harga: 500000, gambar: "https://example.com/package1.jpg " },
      { nama: "Paket 2", harga: 700000, gambar: "https://example.com/package2.jpg " },
    ],
    suvenir: [
      { nama: "Souvenir 1", harga: 50000, gambar: "https://example.com/souvenir1.jpg " },
      { nama: "Souvenir 2", harga: 70000, gambar: "https://example.com/souvenir2.jpg " },
    ],
    likes: 150,
  },
];
